### ISSUE TITLE
Ненужный англицизм на странице "Расширения"

### ISSUE THREAD

**Issue by igormatyushkin014** [phplego/kotlinlang.ru#127]
`Однако, для экстеншн-функций совершенно нормально перегружать функции-члены, которые имеют такое же имя, но другую сигнатуру`

Думаю, `экстеншн-функций` вполне можно заменить на `функций-расширений`. У нас в IT и без того хватает неблагозвучных англицизмов. Ни к чему заводить новые :)

**Comment by phplego** [comment]
Звучит разумно. А как обычно переводят сами разработчики? Есть примеры из статей или книг?
