### ISSUE TITLE
Ошибка в описании sealed class

### ISSUE THREAD

**Issue by AndreiKingsley** [phplego/kotlinlang.ru#194]
https://github.com/phplego/kotlinlang.ru/blob/master/sealed-classes.md

`Чтобы описать изолированный класс, укажите модификатор sealed перед именем класса. Изолированный класс может иметь наследников, но все они должны быть объявлены в том же файле, что и сам изолированный класс.`

Наследники обязаны быть в том же пакете, но не обязательно в файле. В английской версии всё правильно  https://kotlinlang.org/docs/sealed-classes.html#location-of-direct-subclasses

**Comment by StarHamster** [comment]
fixed #196
