### ISSUE TITLE
Проверка статей в "Актуальных задачах"

### ISSUE THREAD

**Issue by Temon137** [phplego/kotlinlang.ru#46]
Мною были проверены обе рекомендованные к проверке статьи:  "Сопрограммы" и "Перегрузка операторов" (и не только они).
Что ещё нужно с ними сделать, чтобы убрать их упоминание в "Актуальных задачах"?

**Comment by phplego** [comment]
Большое спасибо за поправки и проверку! Насколько я помню, у этих двух статей, кроме орфографии, еще была некоторая проблема с читаемостью. Некоторые выражения были написаны так, что воспринимаются тяжело и могут пониматься неоднозначно.
Если считаете, что с этим все более-менее удовлетворительно сейчас, то, чтобы убрать из "требующих проверки", нужно отредактировать файл **INDEX.md** в корне репозитория. Он отвечает за главную страницу.

**Comment by Temon137** [comment]
На мой взгляд, они выглядят вполне удовлетворительно. Уберу упоминание о них на главной странице.
