### ISSUE TITLE
«Встроенные» функции и «изолированные» классы

### ISSUE THREAD

**Issue by Miha-x64** [phplego/kotlinlang.ru#54]
Дословно, встроенные — builtin. inline не встроенные по факту своего существования, а, скорее, встраиваемые, т. к. встраиваются в месте использования.

Изолированные классы — от чего они изолированы? Они, вроде как, [запечатанные](https://www.multitran.ru/c/M.exe?CL=1&s=sealed+class&l1=1).

**Comment by phplego** [comment]
На счет Изолированности. Автор перевода выбрал этот вариант. Остальные поддержали. Он довольно общеупотребимый. Обсуждение корректности этот варианта:

https://rsdn.org/forum/dictionary/2341753.all

**Comment by Leo240** [comment]
@Miha-x64 полностью согласен насчет использования термина "встраиваемые функции".
