### ISSUE TITLE
Выделение ключевых слов внутри строковых выражений

### ISSUE THREAD

**Issue by ardmn** [phplego/kotlinlang.ru#69]
В разделе "Введение" -> "Основной синтаксис" -> "[Использование строковых шаблонов](https://kotlinlang.ru/docs/reference/basic-syntax.html#using-string-templates)" есть следующий код: 
```kotlin
// произвольное выражение в шаблоне:
val s2 = "${s1.replace("is", "was")}, but now is $a"
```
В методе replace "is" - выделяется синим , как ключевое слово но в данном случае  "is" не является ключевым словом. Я бы отредактировал но не знаю как ...

Прикладываю скриншет:
![2017-12-12 23 18 55](https://user-images.githubusercontent.com/7188636/33906621-838ae8d4-df93-11e7-9612-a4c84e491993.png)

**Comment by phplego** [comment]
к сожалению это особенность Javascript библиотеки подсвечивающий синтаксис. Видимо она несовершенна. Тоже не знаю как это обойти

**Comment by ardmn** [comment]
Может быть есть какой-нибудь специфический синтаксис принудительной "не подсветки" ? :)

**Comment by vovaksenov99** [comment]
В контексте проблемы имеет смысл просто заменить слово. Скорее всего библиотека просто подсвечивает слова по шаблону без контекста. Не думаю что тут нужно сильно с этим париться)

**Comment by phplego** [comment]
сделано. Не безупречный перевод, но вроде нормально

![image](https://user-images.githubusercontent.com/3162688/36114362-e6bd14da-1040-11e8-8e47-90b9ebdc0509.png)

**Comment by ruslanys** [comment]
@phplego Может быть "было равно"?

`a было равно 1, но теперь равно 2`?

**Comment by phplego** [comment]
![image](https://user-images.githubusercontent.com/3162688/46851851-9848d800-ce01-11e8-9af0-0bbd11fc53dc.png)
